### ISSUE TITLE
Files app does not open the correct document after editing

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/ios-kDrive#171] opened 2021-06-30 08:07 UTC
Hello,

A PDF opened in the Files application, then annotated, is not taken into account by kDrive.

Each time the document is reopened, the unedited version is displayed. As if the modification was simply not taken into account.

You will see a video describing the problem, note that it worked with the old app.

Device : iPad Pro 11 2018
System : iOS 14.7b4. (also seen on b3 and 14.6)
kDrive : kDrive 4.0.5 and 4.0.5 (13) TestFlight 

Thank you in advance and have a great day.

https://www.swisstransfer.com/d/314e286f-5129-4515-aa08-1c8927d5e671

**Comment by flowbe** [comment] 2021-07-02 12:44
I've been unable to reproduce the issue on my side for now, will try again

**Comment by adrien-pedrina** [comment] 2021-07-09 07:16
New occurrence this morning 

https://user-images.githubusercontent.com/85635056/125038963-4a3a8f00-e096-11eb-941d-85274af42361.mov

**Comment by Lnamw** [comment] 2021-07-27 09:43
This issue seems to have been fixed with the issue #192. After several tests, I am not able to reproduce the bug.

**Closed by Lnamw** 2021-07-27 09:43 UTC
Labels: bug
