### ISSUE TITLE
Select page on a xlsx file

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/ios-kDrive#352] opened 2021-10-20 09:53 UTC
Hello,

I've encountered a problem, if you open an XLS or XLSX document on the mobile app, the preview of the file shows you the possible tabs to select but when you press the button, nothing moves.

I understand that the preview is not meant to be editable, however, it is still quite confusing.

In attachment an explanatory video.

iOS 15.1 RC
kDrive 4.0.12

Thanks in advance

https://user-images.githubusercontent.com/85635056/138071476-1f580d65-6de8-4576-a500-e70608eafaa7.MP4

**Comment by flowbe** [comment] 2021-11-04 07:53
Duplicate of #322

**Closed by flowbe** 2021-11-04 07:53 UTC
Labels: bug
