### ISSUE TITLE
Error in the navigation of the photo backup folder

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/ios-kDrive#249] opened 2021-08-10 07:32 UTC
When I opened the folder where the photos of my iOS device are saved, I got this message. I had to force close the app and restart to get access to my photos.

This is with the penultimate version of the app. Latest version of iOS (14.7.1). I was not able to reproduce the problem with the latest version.

https://www.swisstransfer.com/d/cd3df7f7-bf81-475b-8831-81c68cb8252a

**Comment by flowbe** [comment] 2021-08-10 07:39
Hello, this issue seems to have the same cause as #248. They are both a duplicate of #243 so we are closing this issue and will keep track of the problem there.

**Comment by flowbe** [comment] 2021-08-10 07:40
Duplicate of #243

**Comment by ik-tjacobse** [comment] 2021-08-10 07:40
@flowbe Thank you for your follow-up :)

**Closed by flowbe** 2021-08-10 07:39 UTC
Labels: bug
